website/apps/games/urls.py
from django.conf.urls import url
from apps.games.views import MatchList, MatchDetail, \
    GameList, GameOverview, GameBots, GameBotsActive, GameMatches, \
    PlayerList, PlayerOverview, PlayerBots, PlayerBotsActive, PlayerBotsChallenging, PlayerMatches

urlpatterns = [
    url(r'^$', GameList.as_view(),
        name='index'),

    # ============== GAMES PAGES ==================
    url(r'^games/$', GameList.as_view(),
        name='game-list'),
    url(r'^games/(?P<slug>[-\w]+)/$', GameOverview.as_view(),
        name='game-overview'),

    url(r'^games/(?P<slug>[-\w]+)/bots/$', GameBots.as_view(),
        name='game-bots'),
    url(r'^games/(?P<slug>[-\w]+)/bots/active/$', GameBotsActive.as_view(),
        name='game-bots-active'),

    url(r'^games/(?P<slug>[-\w]+)/matches/$', GameMatches.as_view(),
        name='game-matches'),

    # ============== PLAYERS PAGES ==================
    url(r'^players/$', PlayerList.as_view(),
        name='player-list'),
    url(r'^players/(?P<slug>[-\w]+)/$', PlayerOverview.as_view(),
        name='player-overview'),

    url(r'^players/(?P<slug>[-\w]+)/bots/$', PlayerBots.as_view(),
        name='player-bots'),
    url(r'^players/(?P<slug>[-\w]+)/bots/active/$', PlayerBotsActive.as_view(),
        name='player-bots-active'),
    url(r'^players/(?P<slug>[-\w]+)/bots/challenging/$', PlayerBotsChallenging.as_view(),
        name='player-bots-challenging'),

    url(r'^players/(?P<slug>[-\w]+)/matches/$', PlayerMatches.as_view(),
        name='player-matches'),

    # ============== MATCHES PAGES ==================
    url(r'^matches/$', MatchList.as_view(),
        name='match-list'),
    url(r'^matches/(?P<slug>[-\w]+)/$', MatchDetail.as_view(),
        name='match-detail'),
]

website/hackerrank_tools/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns(
    '',
    url(r'^', include('apps.games.urls', namespace='games')),
    url(r'^admin/', include(admin.site.urls)),
)

website/apps/games/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from solo.models import SingletonModel
from apps.games.managers import FullMatchManager


class Game(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    difficulty = models.FloatField(null=True)
    difficulty_text = models.CharField(max_length=200, null=True)
    slug = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ['pk']

    def __unicode__(self):
        return u'%s' % self.name


class Player(models.Model):
    name = models.CharField(max_length=200, unique=True)
    country = models.CharField(max_length=200, null=True)
    avatar = models.URLField()

    class Meta:
        ordering = ['pk']

    def __unicode__(self):
        return u'%s' % self.name


class Bot(models.Model):
    game = models.ForeignKey(Game)
    player = models.ForeignKey(Player)
    rank = models.PositiveIntegerField()
    score = models.DecimalField(max_digits=15, decimal_places=12)
    language = models.CharField(max_length=200)

    class Meta:
        ordering = ['rank']

    def __unicode__(self):
        return u'%s (%s)' % (self.player, self.game)


class Match(models.Model):
    game = models.ForeignKey(Game)
    bots = models.ManyToManyField(Bot, through='Opponent')
    result = models.PositiveIntegerField()
    message = models.TextField()
    date = models.DateTimeField()
    replay = JSONField(null=True)
    hk_id = models.PositiveIntegerField(unique=True)  # id on hackerrank.com

    objects = models.Manager()
    full_objects = FullMatchManager()

    class Meta:
        ordering = ['-date']

    def get_bots(self):
        return self.bots.order_by('opponent__position')


class Opponent(models.Model):
    match = models.ForeignKey(Match)
    bot = models.ForeignKey(Bot)
    position = models.PositiveIntegerField()

    class Meta:
        ordering = ['position']


class ParsingInfo(SingletonModel):
    oldest_parsed_match = models.PositiveIntegerField(null=True, blank=True)
    newest_parsed_match = models.PositiveIntegerField(null=True, blank=True)

website/apps/games/views.py
from collections import defaultdict
from decimal import Decimal
from django.db.models import Prefetch, Max, Count, Sum
from django.views.generic import ListView, DetailView
from pure_pagination import Paginator, PageNotAnInteger
from apps.games.models import Game, Player, Bot, Match, Opponent


class GameList(ListView):
    model = Game

    def get_context_data(self, **kwargs):
        context = super(GameList, self).get_context_data(**kwargs)
        games = context['game_list']

        # get bot counts for every game
        bot_counts = Bot.objects.values_list('game')\
            .annotate(bot_count=Count('*'))\
            .order_by()
        bot_counts = defaultdict(int, bot_counts)

        for game in games:
            game.bot_count = bot_counts[game.id]

        # get match counts for every game
        match_counts = Match.objects.all().values_list('game')\
            .annotate(match_count=Count('*'))\
            .order_by()
        match_counts = defaultdict(int, match_counts)

        for game in games:
            game.match_count = match_counts[game.id]

        leaders = Bot.objects.filter(rank=1).select_related('player')
        leaders = {bot.game_id: bot.player for bot in leaders}

        game_bots_max = game_matches_max = 0
        if games:
            game_bots_max = max([game.bot_count for game in games])
            game_matches_max = max([game.match_count for game in games])

        for game in games:
            game.leader = leaders[game.id]
            game.difficulty_percent = (1 - game.difficulty) * 100

            game.bots_percent = 0
            if game_bots_max:
                game.bots_percent = float(game.bot_count) / game_bots_max * 100

            game.matches_percent = 0
            if game_matches_max:
                game.matches_percent = float(game.match_count) / game_matches_max * 100

        context.update({
            'game_list': sorted(games, key=lambda game: -game.bot_count),
        })

        return context


class GameDetail(DetailView):
    model = Game
    slug_field = 'slug__iexact'  # case-insensitive match

    def get_object(self, queryset=None):
        game = super(GameDetail, self).get_object()

        game.bots = Bot.objects.filter(game=game)\
            .select_related('player')\
            .annotate(match_count=Count('match'))\
            .prefetch_related(
                Prefetch(
                    'opponent_set',
                    queryset=Opponent.objects.select_related('match')
                )
        )

        game.matches = Match.full_objects.filter(game=game)\
            .prefetch_related(
                Prefetch(
                    'opponent_set',
                    queryset=Opponent.objects.select_related('bot', 'bot__player')
                )
            )

        return game

    def get_context_data(self, **kwargs):
        context = super(GameDetail, self).get_context_data()

        game = self.object

        context.update({
            'bots_count': game.bot_set.count(),
            'last_match': game.match_set.first()
        })

        return context


def calc_bots_stats(bots):
    for bot in bots:
        # count wins/draws/losses
        bot.wins = bot.draws = bot.losses = 0
        for opponent in bot.opponent_set.all():
            match = opponent.match
            if match.result == 0:
                bot.draws += 1
            elif match.result == opponent.position:
                bot.wins += 1
            else:
                bot.losses += 1

        # calc percentages
        bot.win_percent = bot.draw_percent = bot.loss_percent = 0
        match_count = bot.match_count
        if match_count:
            bot.win_percent = float(bot.wins) / match_count * 100
            bot.draw_percent = float(bot.draws) / match_count * 100
            bot.loss_percent = float(bot.losses) / match_count * 100


def calc_relative_strength(match, leader_score):
    match.player, match.opponent = list(match.opponent_set.all())

    # opponents relative score (%)
    player_score = match.player.bot.score / leader_score * 100
    opponent_score = match.opponent.bot.score / leader_score * 100
    score_delta = (player_score - opponent_score) / 2
    match.player_score = 50 + score_delta
    match.opponent_score = 50 - score_delta


class GameOverview(GameDetail):
    bots_limit = 10
    matches_limit = 15

    def get_context_data(self, **kwargs):
        context = super(GameOverview, self).get_context_data()

        game = self.object
        leader_score = game.bot_set.first().score

        # bots stats
        bots = game.bots[:self.bots_limit]
        calc_bots_stats(bots)
        for bot in bots:
            bot.score_percent = bot.score / leader_score * 100

        # matches stats
        matches = game.matches[:self.matches_limit]
        for match in matches:
            calc_relative_strength(match, leader_score)

        context.update({
            'bot_list': bots,
            'match_list': matches,
        })

        return context


class GameBots(GameDetail):
    template_name = 'games/game_bots.html'

    def get_context_data(self, **kwargs):
        context = super(GameBots, self).get_context_data(**kwargs)
        game = self.object
        bots = game.bots

        # paginate
        page_num = self.request.GET.get('page', 1)
        page = Paginator(bots, 50, request=self.request).page(page_num)
        bots = page.object_list

        leader_score = game.bot_set.first().score

        calc_bots_stats(bots)
        for bot in bots:
            bot.score_percent = bot.score / leader_score * 100

        context.update({
            'bot_list': bots,
            'pagination': page,
        })

        return context


class GameBotsActive(GameDetail):
    template_name = 'games/game_bots_active.html'

    def get_context_data(self, **kwargs):
        context = super(GameBotsActive, self).get_context_data(**kwargs)
        game = self.object
        bots = game.bots.order_by('-match_count')

        # paginate
        page_num = self.request.GET.get('page', 1)
        page = Paginator(bots, 50, request=self.request).page(page_num)
        bots = page.object_list

        matches_max = game.bot_set.all() \
            .annotate(match_count=Count('match')) \
            .aggregate(Max('match_count'))['match_count__max']

        calc_bots_stats(bots)
        for bot in bots:
            bot.matches_percent = 0
            if matches_max:
                bot.matches_percent = float(bot.match_count) / matches_max * 100

        context.update({
            'bot_list': bots,
            'pagination': page,
        })

        return context


class GameMatches(GameDetail):
    template_name = 'games/game_matches.html'

    def get_context_data(self, **kwargs):
        context = super(GameMatches, self).get_context_data(**kwargs)
        game = self.object
        matches = game.matches

        # paginate
        page_num = self.request.GET.get('page', 1)
        page = Paginator(matches, 50, request=self.request).page(page_num)
        matches = page.object_list

        leader_score = game.bot_set.first().score

        for match in matches:
            calc_relative_strength(match, leader_score)

        context.update({
            'match_list': matches,
            'pagination': page,
        })

        return context


class PlayerList(ListView):
    model = Player
    ordering = ['-score']  # see annotates below

    def get_queryset(self):
        queryset = super(PlayerList, self).get_queryset()

        queryset = queryset.prefetch_related(
            Prefetch(
                'bot_set',
                to_attr='bots'
            )
        ).annotate(
            score=Sum('bot__score'),
        )

        return queryset

    def get_context_data(self, **kwargs):
        context = super(PlayerList, self).get_context_data(**kwargs)
        players = context['player_list']

        # used to check if bot is in Top 10% by score
        games = Game.objects.annotate(max_score=Max('bot__score'))

        # calc overall best results
        bots_max = Player.objects\
            .annotate(bot_count=Count('bot'))\
            .aggregate(Max('bot_count'))['bot_count__max']

        matches_max = Player.objects\
            .annotate(match_count=Count('bot__match'))\
            .aggregate(Max('match_count'))['match_count__max']

        score_max = Player.objects\
            .annotate(score=Sum('bot__score'))\
            .aggregate(Max('score'))['score__max']

        top1_max = Bot.objects.filter(rank=1).values('player_id')\
            .annotate(top1_count=Count('*'))\
            .aggregate(Max('top1_count'))['top1_count__max']

        top10_counts = defaultdict(int)
        for bot in Bot.objects.all():
            game = next(x for x in games if x.id == bot.game_id)
            if bot.score >= game.max_score * Decimal(0.9):
                top10_counts[bot.player_id] += 1  # top 10% by score on this game

        top10_max = 0
        if top10_counts:
            top10_max = max(top10_counts.values())

        # paginate
        page_num = self.request.GET.get('page', 1)
        page = Paginator(players, 50, request=self.request).page(page_num)
        players = page.object_list

        player_ids = [player.id for player in players]

        # absolute stats
        for player in players:
            player.top1 = player.top10 = 0

            for bot in player.bots:
                game = next(x for x in games if x.pk == bot.game_id)

                if bot.rank == 1:
                    player.top1 += 1
                if bot.score >= game.max_score * Decimal(0.9):
                    player.top10 += 1  # top 10% of score for this game

        bot_counts = Bot.objects.order_by()\
            .filter(player__in=player_ids)\
            .values('player')\
            .annotate(bot_count=Count('*'))\
            .values_list('player', 'bot_count')

website/apps/games/templates/games/game_bots.html
{% extends "games/game_detail.html" %}

{% block game-page-title %}Bots{% endblock %}

{% block game-content %}
<section>
<header>Game bots
    <small>All</small>
</header>

<footer>
    <nav>
        {% with request.resolver_match.url_name as page %}
        <ul>
            <li class="{% if page == 'game-bots' %}active{% endif %}">
                {% url 'games:game-bots' game.slug as url %}
                <a href="{{ url }}">Most Successful</a></li>

            <li class="{% if page == 'game-bots-active' %}active{% endif %}">
                {% url 'games:game-bots-active' game.slug as url %}
                <a href="{{ url }}">Most Active</a></li>
        </ul>
        {% endwith %}
    </nav>
</footer>

<article>
    {% include 'pagination.html' with page_obj=pagination %}

    {% block game-bots-content %}
    <div class="table-responsive">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th class="col-xs-1 cell-centered">Rank</th>
                    <th class="col-xs-3">Player</th>
                    <th class="col-xs-3">Score</th>
                    <th class="col-xs-2">Language</th>
                    <th class="col-xs-3">Winrate</th>
                </tr>
            </thead>
            <tbody>
            {% for bot in bot_list %}
                {% url 'games:player-overview' bot.player.name as player_url %}

                <tr class="bot-row" data-link="{{ player_url }}">
                    <td class="cell-centered">
                        {{ bot.rank }}
                    </td>
                    <td class="player">
                        <div class="avatar">
                            <a href="{{ player_url }}">
                                <img src="{{ bot.player.avatar }}">
                            </a>
                        </div>
                        <a href="{{ player_url }}"> {{ bot.player.name }} </a>
                        <div class="subtext">
                            {{ bot.player.country }}
                        </div>
                    </td>
                    <td>
                        {{ bot.score|floatformat:2 }}
                        <div class="color-bar">
                            <div class="player" style="width: {{ bot.score_percent }}%"></div>
                        </div>
                    </td>
                    <td>
                        {{ bot.language }}
                    </td>
                    <td>
                        {{ bot.win_percent|floatformat:2 }}%
                        <div class="color-bar">
                            <div class="win" style="width: {{ bot.win_percent }}%"></div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock game-bots-content %}

    {% include 'pagination.html' with page_obj=pagination force_numbers=True %}
</article>
</section>
{% endblock game-content %}

website/apps/games/templates/games/game_overview_matches.html
<section>
<header>Latest matches
{#    <div class="more">#}
{#        <a href="{% url 'games:player-matches' player.name %}">#}
{#            <i class="fa fa-plus-square"></i> more#}
{#        </a>#}
{#    </div>#}
</header>

<article>
    <div class="table-responsive">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th class="col-xs-2">Match ID</th>
                    <th class="col-xs-3">Player 1</th>
                    <th class="col-xs-3">Player 2</th>
                    <th class="col-xs-2">Relative strength (%)</th>
                </tr>
            </thead>
            <tbody>
            {% for match in match_list %}
                {% url 'games:match-detail' match.hk_id as match_url %}

                <tr class="match-row" data-link="{{ match_url }}">
                    <td>
                        <div>
                            <a class="match_id" href="{{ match_url }}">
                                {{ match.hk_id }}
                            </a>
                        </div>
                        <time class="timeago subtext"
                              datetime="{{ match.date|date:"c" }}"
                              title="{{ match.date }}">
                            {{ match.date }}
                        </time>
                    </td>

                    {% for opponent in match.opponent_set.all %}
                        {% url 'games:player-overview' opponent.bot.player.name as player_url %}

                        <td class="opponent">
                            <div class="avatar">
                                <a href="{{ player_url }}">
                                    <img src="{{ opponent.bot.player.avatar }}">
                                </a>
                            </div>
                            <a href="{{ player_url }}">
                                {{ opponent.bot.player.name }}
                                {% if match.result == forloop.counter %}
                                    <i class="fa fa-check"></i>
                                {% endif %}
                            </a>
                            <div class="subtext">
                                {{ opponent.bot.player.country }}
                            </div>
                        </td>
                    {% endfor %}

                    <td>
                        <span>{{ match.player_score|floatformat:0 }}</span>
                        <span class="sep">/</span>
                        <span>{{ match.opponent_score|floatformat:0 }}</span>
                        <div class="color-bar">
                            <div class="player" style="width: {{ match.player_score }}%"></div>
                            <div class="opponent" style="width: {{ match.opponent_score }}%"></div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</article>
</section>

website/apps/games/templates/games/games_table_body.html
{% for game in game_list %}
    <!-- color row accordingly to game difficulty -->
    {% if game.difficulty == "Difficult" %}
        <tr class="game_row warning">
    {% elif game.difficulty == "Expert" %}
        <tr class="game_row danger">
    {% else %}
        <tr class="game_row success">
    {% endif %}
            <td> {{ game.name }} </td>
            <td> {{ game.difficulty}} </td>
        </tr>
{% endfor %}

website/apps/games/templates/games/match_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_scripts %}
    <script src="{% static 'games/js/base.js' %}"></script>
{% endblock page_scripts %}

{% block page_styles %}
    <link rel="stylesheet" href="{% static 'games/css/base.css' %}">
{% endblock page_styles %}

{% block content %}

<div class="page-overview">
    <div class="page-overview-primary">
        <div class="page-overview-title">
            <h1> Matches
                <small>Overview</small>
            </h1>
        </div>
    </div>
</div>

<section>
<article>
    {% include 'pagination.html' with page_obj=pagination %}

    <div class="table-responsive">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th class="col-xs-2">Match ID</th>
                    <th class="col-xs-2">Game</th>
                    <th class="col-xs-3">Player 1</th>
                    <th class="col-xs-3">Player 2</th>
                    <th class="col-xs-2">Relative strength (%)</th>
                </tr>
            </thead>
            <tbody>
            {% for match in match_list %}
                {% url 'games:match-detail' match.hk_id as match_url %}
                {% url 'games:game-overview' match.game.slug as game_url %}

                <tr class="match-row" data-link="{{ match_url }}">
                    <td>
                        <div>
                            <a class="match_id" href="{{ match_url }}">
                                {{ match.hk_id }}
                            </a>
                        </div>
                        <time class="timeago subtext"
                              datetime="{{ match.date|date:"c" }}"
                              title="{{ match.date }}">
                            {{ match.date }}
                        </time>
                    </td>
                    <td>
                        <a class="link-white" href="{{ game_url }}">
                            {{ match.game }}
                        </a>
                    </td>

                    {% for opponent in match.opponent_set.all %}
                        {% url 'games:player-overview' opponent.bot.player.name as player_url %}

                        <td class="opponent">
                            <div class="avatar">
                                <a href="{{ player_url }}">
                                    <img src="{{ opponent.bot.player.avatar }}">
                                </a>
                            </div>
                            <a href="{{ player_url }}">
                                {{ opponent.bot.player.name }}
                                {% if match.result == forloop.counter %}
                                    <i class="fa fa-check"></i>
                                {% endif %}
                            </a>
                            <div class="subtext">
                                {{ opponent.bot.player.country }}
                            </div>
                        </td>
                    {% endfor %}

                    <td>
                        <span>{{ match.player_score|floatformat:0 }}</span>
                        <span class="sep">/</span>
                        <span>{{ match.opponent_score|floatformat:0 }}</span>
                        <div class="color-bar">
                            <div class="player" style="width: {{ match.player_score }}%"></div>
                            <div class="opponent" style="width: {{ match.opponent_score }}%"></div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'pagination.html' with page_obj=pagination force_numbers=True %}
</article>
</section>
{% endblock %}

website/apps/games/templates/games/player_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page_scripts %}
    <script src="{% static 'games/js/base.js' %}"></script>
{% endblock page_scripts %}

{% block page_styles %}
    <link rel="stylesheet" href="{% static 'games/css/base.css' %}">
{% endblock page_styles %}

{% block content %}
    {% url 'games:player-overview' player.name as player_url %}

    <div class="page-overview">
        <div class="page-overview-primary">
            <div class="avatar">
                <a href="{{ player_url }}">
                    <img src="{{ player.avatar }}" alt="{{ player.name }}">
                </a>
            </div>
            <div class="page-overview-title">
                <h1> {{ player.name }}
                    <small class="country">({{ player.country }})</small>
                    <small>{% block player-page-title %}Overview{% endblock %}</small>
                </h1>
            </div>
        </div>

        <div class="page-overview-secondary">
            <dl>
                <dd>
                    <time class="timeago"
                          datetime="{{ match_list.first.date|date:'c' }}"
                          title="{{ match_list.first.date }}">
                        {{ last_match.date|date:'c'|default:'-' }}
                    </time>
                </dd>
                <dt>Last Match</dt>
            </dl>
            <dl>
                <dd>
                    <span class="match-record">
                        <span class="wins">{{ wins }}</span>
                        <span class="sep">-</span>
                        <span class="draws">{{ draws }}</span>
                        <span class="sep">-</span>
                        <span class="losses">{{ losses }}</span>
                    </span>
                </dd>
                <dt>Record</dt>
            </dl>
            <dl>
                <dd>{{ winrate|floatformat:2 }}%</dd>
                <dt>Win Rate</dt>
            </dl>
        </div>
    </div>

    <div class="page-menu">
        {% url 'games:player-bots' player.name as player_bots_url %}
        {% url 'games:player-matches' player.name as player_matches_url %}

        <nav class="menu-links">
            {% with request.resolver_match.url_name as page %}
            <ul>
                <li class="{% if page == 'player-overview' %}active{% endif %}">
                    <a href="{{ player_url }}">Overview</a></li>

                <li class="{% if 'player-bots' in page %}active{% endif %}">
                    <a href="{{ player_bots_url }}">Bots</a></li>

                <li class="{% if page == 'player-matches' %}active{% endif %}">
                    <a href="{{ player_matches_url }}">Matches</a></li>
            </ul>
            {% endwith %}
        </nav>
    </div>

    {% block player-content %}
        {% include 'games/player_overview_bots.html' %}
        {% include 'games/player_overview_matches.html' %}
    {% endblock player-content %}
{% endblock content %}

website/apps/games/templates/games/player_overview_matches.html
<section>
<header>Latest matches
    <div class="more">
        <a href="{% url 'games:player-matches' player.name %}">
            <i class="fa fa-plus-square"></i> more
        </a>
    </div>
</header>

<article>
    <div class="table-responsive table-borderless">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th class="col-xs-3">Opponent</th>
                    <th class="col-xs-2">Result</th>
                    <th class="col-xs-2">Game</th>
                    <th class="col-xs-2">Win chance</th>
                    <th class="col-xs-3">Rank Me<span class="sep">/</span>Him</th>
                </tr>
            </thead>
            <tbody>
            {% for match in match_list %}
                {% url 'games:match-detail' match.hk_id as match_url %}
                {% url 'games:game-overview' match.game.slug as game_url %}
                {% url 'games:player-overview' match.opponent_name as opponent_url %}

                <tr class="match-row" data-link="{{ match_url }}">
                    <td class="opponent">
                        <div class="avatar">
                            <a href="{{ opponent_url }}">
                                <img src="{{ match.opponent.bot.player.avatar }}">
                            </a>
                        </div>
                        <a href="{{ opponent_url }}"> {{ match.opponent_name }} </a>
                        <div class="subtext">
                            {{ match.opponent.bot.player.country }}
                        </div>
                    </td>

                    <td>
                    {% if match.result == 0 %}
                        <div class="draw">
                    {% elif match.result == match.opponent.position %}
                        <div class="loss">
                    {% else %}
                        <div class="win">
                    {% endif %}
                            {{ match.result_text }}
                        </div>
                        <time class="timeago subtext"
                              datetime="{{ match.date|date:"c" }}"
                              title="{{ match.date }}">
                            {{ match.date }}
                        </time>
                    </td>

                    <td>
                        <a href="{{ game_url }}"> {{ match.game }} </a>
                    </td>
                    <td>
                        {{ match.win_chance|floatformat:2 }}%
                        <div class="color-bar">
                            <div style="width: {{ match.win_chance }}%"></div>
                        </div>
                    </td>
                    <td>
                        <span>{{ match.player.bot.rank }}</span>
                        <span class="sep">/</span>
                        <span>{{ match.opponent.bot.rank }}</span>
                        <div class="color-bar">
                            <div class="player" style="width: {{ match.player_rank }}%"></div>
                            <div class="opponent" style="width: {{ match.opponent_rank }}%"></div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</article>
</section>