website/apps/games/urls.py
from django.conf.urls import url
from apps.games.views import MatchList, MatchDetail, \
    GameList, GameOverview, GameBots, GameBotsActive, GameMatches, \
    PlayerList, PlayerOverview, PlayerBots, PlayerBotsActive, PlayerBotsChallenging, PlayerMatches

urlpatterns = [
    url(r'^$', GameList.as_view(),
        name='index'),

    # ============== GAMES PAGES ==================
    url(r'^games/$', GameList.as_view(),
        name='game-list'),
    url(r'^games/(?P<slug>[-\w]+)/$', GameOverview.as_view(),
        name='game-overview'),

    url(r'^games/(?P<slug>[-\w]+)/bots/$', GameBots.as_view(),
        name='game-bots'),
    url(r'^games/(?P<slug>[-\w]+)/bots/active/$', GameBotsActive.as_view(),
        name='game-bots-active'),

    url(r'^games/(?P<slug>[-\w]+)/matches/$', GameMatches.as_view(),
        name='game-matches'),

    # ============== PLAYERS PAGES ==================
    url(r'^players/$', PlayerList.as_view(),
        name='player-list'),
    url(r'^players/(?P<slug>[-\w]+)/$', PlayerOverview.as_view(),
        name='player-overview'),

    url(r'^players/(?P<slug>[-\w]+)/bots/$', PlayerBots.as_view(),
        name='player-bots'),
    url(r'^players/(?P<slug>[-\w]+)/bots/active/$', PlayerBotsActive.as_view(),
        name='player-bots-active'),
    url(r'^players/(?P<slug>[-\w]+)/bots/challenging/$', PlayerBotsChallenging.as_view(),
        name='player-bots-challenging'),

    url(r'^players/(?P<slug>[-\w]+)/matches/$', PlayerMatches.as_view(),
        name='player-matches'),

    # ============== MATCHES PAGES ==================
    url(r'^matches/$', MatchList.as_view(),
        name='match-list'),
    url(r'^matches/(?P<slug>[-\w]+)/$', MatchDetail.as_view(),
        name='match-detail'),
]

website/hackerrank_tools/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns(
    '',
    url(r'^', include('apps.games.urls', namespace='games')),
    url(r'^admin/', include(admin.site.urls)),
)

website/templates/base.html
{% load staticfiles %}

{%  spaceless %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Hackerrank-tools{% endblock title %}</title>

        <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />

        {% block common_scripts %}
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
            <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.4.3/jquery.timeago.min.js"></script>
        {% endblock common_scripts %}

        {% block common_styles %}
            <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
            <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
            <link href="{% static 'css/screen.css' %}" media="screen, projection" rel="stylesheet">
        {% endblock common_styles %}

        {% block page_scripts %}
        {% endblock page_scripts %}

        {% block page_styles %}
        {% endblock page_styles %}
    </head>

    <body>
        <div class="menu-primary">
            <div class="container col-md-9">
                <a class="menu-logo" href="{% url 'games:index' %}">Hackerrank-tools</a>
                <nav class="menu-links">
                    <ul>
                        <li><a href="{% url 'games:game-list' %}">Games</a></li>
                        <li><a href="{% url 'games:player-list' %}">Players</a></li>
                        <li><a href="{% url 'games:match-list' %}">Matches</a></li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="container container-main col-md-9">
            {% block content %}
            {% endblock content %}
        </div> <!-- container -->

        <div class="container col-md-9">
            <div class="footer-nav">
                    <nav>
                        <ul>
                            <li><a href="/pages/about">About</a></li>
                            <li><a href="/pages/about">Technical stack</a></li>
                            <li><a href="/pages/about">Acknowledgments</a></li>
                            <li><a href="/pages/about">Github</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
    </body>
</html>
{%  endspaceless %}

website/templates/pagination.html
{% if page_obj.paginator.num_pages > 1 or force_numbers %}
    <div class="pagination-info">
        {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }}
    </div>
{% endif %}

{% if page_obj.paginator.num_pages > 1 %}
    <nav class="pagination">
        {% if page_obj.has_previous %}
            <span>
                <a href="?{{ page_obj.first_page_number.querystring }}">
                    &laquo; First
                </a>
            </span>
            <span>
                <a href="?{{ page_obj.previous_page_number.querystring }}">
                    &lsaquo; Prev
                </a>
            </span>
        {% endif %}

        {% for page in page_obj.pages %}
            {% if page %}
                {% if page == page_obj.number %}
                    <span class="page-current">
                        {{ page }}
                    </span>
                {% else %}
                    <span>
                        <a href="?{{ page.querystring }}">
                            {{ page }}
                        </a>
                    </span>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <span>
                <a href="?{{ page_obj.next_page_number.querystring }}">
                    Next &rsaquo;
                </a>
            </span>
            <span>
                <a href="?{{ page_obj.last_page_number.querystring }}">
                    Last &raquo;
                </a>
            </span>
        {% endif %}
    </nav>
{% endif %}